import numpy as np
from pipeline import Pipeline_for_task_2
import tensorflow as tf
import PIL
from ner_model_class import NERmodel
from PIL import Image


path_to_image='C:/Users/user/PycharmProjects/testovoe___1/task_2/test_data/Dog/Dog-Test (1).jpg'

string= "The Unicorn pranced under the rainbow."

classification_model_path='image_classification_model.h5'
entity_recognition_model_path='./trained_ner_model'


pipeline=Pipeline_for_task_2(classification_model_path,entity_recognition_model_path)


image=np.asarray(Image.open(fr"{path_to_image}").convert('L').resize((64,64)))
train_texts = [
    "I saw a Beetle in the garden today.",
    "The Butterfly gracefully fluttered by.",
    "My Cat loves to sleep on the couch.",
    "We have a Cow in our farm.",
    "The Dog barked loudly at the mailman.",
    "An Elephant is a majestic creature.",
    "I saw a Gorilla at the zoo.",
    "The Hippo was swimming in the river.",
    "A Lizard was sunbathing on the rock.",
    "The Monkey swung from tree to tree.",
    "A Mouse scurried across the floor.",
    "The Panda was eating bamboo.",
    "There was a Spider in the corner of the room.",
    "The Tiger roared in the jungle.",
    "A Zebra galloped across the savannah.",
    "I wish I had a pet Unicorn.",
    "The Rabbit hopped away quickly.",
    "The Fish swam in the aquarium.",
    "The Parrot mimicked our words.",
    "The Dolphin jumped out of the water.",
    "The Kangaroo jumped high.",
    "The Sheep were grazing in the field.",
    "The Owl hooted in the night.",
    "Our Cat chased a Mouse.",
    "The Cow was grazing near the barn.",
    "A Dog ran across the street.",
    "The Elephant trumpeted loudly.",
    "The Gorilla beat its chest.",
    "The Hippo opened its large mouth.",
    "A Lizard scurried up the tree.",
    "The Monkey ate a banana.",
    "A Mouse hid under the bed.",
    "The Panda climbed the tree.",
    "There was a Spider web in the corner.",
    "The Tiger prowled through the jungle.",
    "The Zebra grazed on the grass.",
    "A Lion roared across the savannah.",
    "The Unicorn pranced under the rainbow.",
    "A Rabbit nibbled on a carrot.",
    "The Bear hibernated in its cave.",
    "An Alligator lurked in the swamp.",
    "The Shark circled in the ocean.",
    "A Deer grazed in the meadow.",
    "The Squirrel gathered nuts.",
    "The Owl hooted softly at night.",
    "The Panda rolled playfully on the grass.",
    "A Spider spun a web in the garden.",
    "The Tiger stalked its prey silently.",
    "The Lion basked in the sun.",
    "A Bear lumbered through the forest.",
    "A Fish darted around the coral reef.",
    "A Dolphin swam gracefully alongside the boat.",
    "A Shark sliced through the water.",
    "A Deer bounded gracefully.",
    "The Sheep grazed on the hillside.",
    "A Squirrel chattered in the tree.",
    "The Owl stared with large, round eyes.",
    "In the grass hopped the Rabbit.",
    "Majestically glided the Eagle above the cliffs.",
    "On the branch sat the Robin.",
    "Across the field ran the Fox.",
    "Under the tree rested the Deer.",
    "In the sky soared the Hawk.",
    "At the pond drank the Elk.",
    "Near the shore lay the Seal.",
    "On the rock basked the Snake.",
    "Around the yard chased the Chickens.",
    "In the forest howled the Wolf.",
    "Across the plains roamed the Bison.",
    "On the roof perched the Pigeon.",
    "In the river swam the Otter.",
    "In the ocean leaped the Whale.",
    "In the garden sang the Canary.",
    "In the shadows crept the Panther.",
    "Under the leaves hid the Hedgehog.",
    "In the meadow flew the Butterfly.",
    "On the lily pad sat the Frog.",
    "Near the hive buzzed the Bee.",
    "In the alley prowled the Cat.",
    "At the edge of the forest stalked the Lynx.",
    "In the waterhole wallowed the Buffalo.",
    "Across the valley echoed the call of the Coyote.",
    "In the burrow slept the Mole.",
    "On the cliff stood the Mountain Goat.",
    "In the cave hibernated the Bear.",
    "On the fence roosted the Rooster.",
    "In the barn lived the Pig.",
    "On the lawn hunted the Falcon.",
    "In the jungle swung the Lemur.",
    "On the beach scurried the Crab.",
    "In the bushes rustled the Hedgehog.",
    "Over the meadow flew the Skylark.",
    "On the rock warmed itself the Iguana.",
    "In the pond splashed the Duck.",
    "Under the leaves hid the Snail.",
    "On the tree bark rested the Gecko.",
    "On the wall climbed the Tarantula.",
    "In the sky circled the Osprey.",
    "Over the field hunted the Kestrel.",
    "In the flower sat the Ladybug.",
    "At the water's edge stood the Heron.",
    "In the tall grass slithered the Python.",
    "Under the log hid the Salamander.",
    "In the reed sang the Warbler.",
    "Above the meadow hovered the Dragonfly.",
    "On the leaf crawled the Caterpillar.",
    "In the shadows prowled the Jaguar.",
    "Across the yard scuttled the Beetle.",
    "In the canopy swung the Gibbon.",
    "By the stream relaxed the Capybara.",
    "In the open field ran the Gazelle.",
    "Under the bush slept the Dormouse.",
    "In the cage chirped the Finch.",
    "On the riverbank basked the Crocodile.",
    "Near the mountain roared the Snow Leopard.",
    "In the trees howled the Howler Monkey.",
    "By the stream lounged the Water Buffalo.",
    "In the shadows crept the Leopard.",
    "On the rooftop prowled the Cat.",
    "In the barn slept the Horse.",
    "At the edge of the lake sang the Frog.",
    "In the field played the Rabbit.",
    "In the sky wheeled the Gull.",
    "On the leaf hid the Chameleon.",
    "The Beetle scurried under the fallen log.",
    "A Butterfly rested on the daisy.",
    "The Cat chased its own tail in circles.",
    "The Cow lay down in the shade.",
    "The Dog fetched the ball enthusiastically.",
    "An Elephant splashed water with its trunk.",
    "The Gorilla ate bananas in the enclosure.",
    "A Lizard climbed up the wall effortlessly.",
    "The Monkey stole a piece of fruit.",
    "A Mouse peeked out of its hole.",
    "The Panda slept soundly on a tree branch.",
    "A Spider hung from its silk thread.",
    "The Tiger's stripes blended into the foliage.",
    "A Lioness led her cubs through the grass.",
    "A Rabbit snuggled into the hay.",
    "The Bear found a honeycomb.",
    "A Fish swam playfully with its school.",
    "The Parrot whistled a tune.",
    "The Dolphin performed tricks for the audience.",
    "An Alligator snapped its jaws shut.",
    "The Shark glided silently beneath the surface.",
    "The Kangaroo carried its joey in its pouch.",
    "A Deer drank from the clear stream.",
    "A Squirrel buried its acorn.",
    "The Owl stared with large, round eyes.",
    "In the grass hopped the Rabbit.",
    "The Beetle crawled slowly on the leaf.",
    "The Butterfly landed softly on the flower.",
    "The Cat watched the birds from the window.",
    "The Cow gave us fresh milk every morning.",
    "The Dog loves to play fetch in the park.",
    "The Elephant trumpeted loudly in the distance.",
    "The Gorilla plays with its young in the zoo.",
    "The Hippo submerged itself in the cool water.",
    "The Lizard basked in the sun on the rock.",
    "The Monkey swung playfully from branch to branch.",
    "The Mouse darted quickly to avoid the cat.",
    "The Panda loves to munch on bamboo shoots.",
    "The Spider spun a beautiful web in the corner.",
    "The Tiger prowled silently through the tall grass.",
    "The Zebra's stripes are unique and beautiful."
]
ner_model=NERmodel(entity_recognition_model_path)
rr=[ner_model.predict(train_texts[i]) for i in range(len(train_texts))]


image=image.reshape((-1, 64, 64,1))

result=pipeline.evaluate(image,string)

print(f'Result of pipeline: {result}')

